<?php

namespace Database\Seeders;

use App\Models\Setting;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class SettingSeeder extends Seeder
{
    use WithoutModelEvents;

    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $settings = [
            [
                'group' => 'general',
                'key' => 'general.site_name',
                'value' => 'Đoàn TNTT Gx Mỹ Vân',
                'type' => 'string',
                'label' => 'Tên website',
                'description' => 'Tên website công khai được hiển thị ở tiêu đề và trên trình duyệt.',
                'is_public' => true,
                'is_encrypted' => false,
                'autoload' => true,
                'sort_order' => 10,
            ],
            [
                'group' => 'general',
                'key' => 'general.site_tagline',
                'value' => 'Nền tảng quản lý thiếu nhi giáo xứ',
                'type' => 'string',
                'label' => 'Khẩu hiệu website',
                'description' => 'Mô tả ngắn được dùng ở màn hình đăng nhập và các bề mặt thương hiệu.',
                'is_public' => true,
                'is_encrypted' => false,
                'autoload' => true,
                'sort_order' => 20,
            ],
            [
                'group' => 'general',
                'key' => 'general.site_email',
                'value' => 'tntt.myvan@gmail.com',
                'type' => 'string',
                'label' => 'Email website',
                'description' => 'Địa chỉ email liên hệ chính công khai của website.',
                'is_public' => true,
                'is_encrypted' => false,
                'autoload' => true,
                'sort_order' => 30,
            ],
            [
                'group' => 'general',
                'key' => 'general.site_phone',
                'value' => '',
                'type' => 'string',
                'label' => 'Số điện thoại website',
                'description' => 'Số điện thoại liên hệ chính công khai của website.',
                'is_public' => true,
                'is_encrypted' => false,
                'autoload' => true,
                'sort_order' => 40,
            ],
            [
                'group' => 'general',
                'key' => 'general.meta_keywords',
                'value' => '',
                'type' => 'string',
                'label' => 'Từ khóa meta',
                'description' => 'Các từ khóa SEO dùng cho website công khai.',
                'is_public' => true,
                'is_encrypted' => false,
                'autoload' => true,
                'sort_order' => 50,
            ],
            [
                'group' => 'general',
                'key' => 'general.meta_description',
                'value' => '',
                'type' => 'string',
                'label' => 'Mô tả meta',
                'description' => 'Mô tả SEO dùng cho website công khai.',
                'is_public' => true,
                'is_encrypted' => false,
                'autoload' => true,
                'sort_order' => 60,
            ],
            [
                'group' => 'social',
                'key' => 'social.facebook_url',
                'value' => '',
                'type' => 'string',
                'label' => 'Liên kết Facebook',
                'description' => 'Liên kết trang Facebook công khai của website.',
                'is_public' => true,
                'is_encrypted' => false,
                'autoload' => true,
                'sort_order' => 70,
            ],
            [
                'group' => 'social',
                'key' => 'social.instagram_url',
                'value' => '',
                'type' => 'string',
                'label' => 'Liên kết Instagram',
                'description' => 'Liên kết trang Instagram công khai của website.',
                'is_public' => true,
                'is_encrypted' => false,
                'autoload' => true,
                'sort_order' => 80,
            ],
            [
                'group' => 'social',
                'key' => 'social.youtube_url',
                'value' => '',
                'type' => 'string',
                'label' => 'Liên kết YouTube',
                'description' => 'Liên kết kênh YouTube công khai của website.',
                'is_public' => true,
                'is_encrypted' => false,
                'autoload' => true,
                'sort_order' => 90,
            ],
            [
                'group' => 'social',
                'key' => 'social.tiktok_url',
                'value' => '',
                'type' => 'string',
                'label' => 'Liên kết TikTok',
                'description' => 'Liên kết trang TikTok công khai của website.',
                'is_public' => true,
                'is_encrypted' => false,
                'autoload' => true,
                'sort_order' => 100,
            ],
            [
                'group' => 'branding',
                'key' => 'branding.logo',
                'value' => 'images/sites/LOGO-20260321040347-a2jpbb6c.png',
                'type' => 'image',
                'label' => 'Logo',
                'description' => 'Hình ảnh thương hiệu chính được dùng trong khung ứng dụng.',
                'is_public' => true,
                'is_encrypted' => false,
                'autoload' => true,
                'sort_order' => 110,
            ],
            [
                'group' => 'branding',
                'key' => 'branding.favicon',
                'value' => 'images/sites/FAVICON_default.png',
                'type' => 'image',
                'label' => 'Favicon',
                'description' => 'Biểu tượng trình duyệt hiển thị cho website.',
                'is_public' => true,
                'is_encrypted' => false,
                'autoload' => true,
                'sort_order' => 120,
            ],
            [
                'group' => 'branding',
                'key' => 'branding.login_image',
                'value' => 'images/sites/login_default.png',
                'type' => 'image',
                'label' => 'Hình đăng nhập',
                'description' => 'Hình ảnh hiển thị ở giao diện đăng nhập chia cột.',
                'is_public' => true,
                'is_encrypted' => false,
                'autoload' => true,
                'sort_order' => 130,
            ],
            [
                'group' => 'theme',
                'key' => 'theme.preset',
                'value' => 'sky',
                'type' => 'string',
                'label' => 'Mẫu giao diện',
                'description' => 'Mẫu giao diện được chọn để áp dụng màu sắc cho website.',
                'is_public' => true,
                'is_encrypted' => false,
                'autoload' => true,
                'sort_order' => 70,
            ],
            [
                'group' => 'theme',
                'key' => 'theme.neutral_palette',
                'value' => 'gray',
                'type' => 'string',
                'label' => 'Bảng màu trung tính',
                'description' => 'Bảng màu trung tính được dùng cho nền và các tông xám của giao diện.',
                'is_public' => true,
                'is_encrypted' => false,
                'autoload' => true,
                'sort_order' => 75,
            ],
            [
                'group' => 'theme',
                'key' => 'theme.seasonal_enabled',
                'value' => '0',
                'type' => 'boolean',
                'label' => 'Bật giao diện theo mùa',
                'description' => 'Bật các giao diện đặc biệt cho mùa hoặc sự kiện.',
                'is_public' => true,
                'is_encrypted' => false,
                'autoload' => true,
                'sort_order' => 80,
            ],
            [
                'group' => 'mail',
                'key' => 'mail.from_name',
                'value' => 'Đoàn TNTT giáo xứ Mỹ Vân',
                'type' => 'string',
                'label' => 'Tên người gửi email',
                'description' => 'Tên người gửi mặc định cho các email được gửi đi.',
                'is_public' => false,
                'is_encrypted' => false,
                'autoload' => true,
                'sort_order' => 90,
            ],
            [
                'group' => 'mail',
                'key' => 'mail.from_address',
                'value' => 'no-reply@tnttgxmyvan.org',
                'type' => 'string',
                'label' => 'Địa chỉ email gửi đi',
                'description' => 'Địa chỉ email người gửi mặc định cho các email được gửi đi.',
                'is_public' => false,
                'is_encrypted' => false,
                'autoload' => true,
                'sort_order' => 100,
            ],
            [
                'group' => 'mail',
                'key' => 'mail.reply_to_address',
                'value' => 'tntt.myvan@gmail.com',
                'type' => 'string',
                'label' => 'Địa chỉ phản hồi',
                'description' => 'Địa chỉ được dùng khi người nhận trả lời email.',
                'is_public' => false,
                'is_encrypted' => false,
                'autoload' => true,
                'sort_order' => 110,
            ],
            [
                'group' => 'mail',
                'key' => 'mail.username',
                'value' => 'no-reply@tnttgxmyvan.org',
                'type' => 'string',
                'label' => 'Tên đăng nhập SMTP',
                'description' => 'Tên đăng nhập dùng để xác thực với máy chủ SMTP.',
                'is_public' => false,
                'is_encrypted' => false,
                'autoload' => true,
                'sort_order' => 120,
            ],
            [
                'group' => 'mail',
                'key' => 'mail.password',
                'value' => 'MucDongIT@2025',
                'type' => 'string',
                'label' => 'Mật khẩu SMTP',
                'description' => 'Mật khẩu dùng để xác thực với máy chủ SMTP.',
                'is_public' => false,
                'is_encrypted' => true,
                'autoload' => false,
                'sort_order' => 130,
            ],
            [
                'group' => 'mail',
                'key' => 'mail.mailer',
                'value' => 'smtp',
                'type' => 'string',
                'label' => 'Giao thức gửi mail',
                'description' => 'Giao thức gửi email mặc định của hệ thống.',
                'is_public' => false,
                'is_encrypted' => false,
                'autoload' => true,
                'sort_order' => 140,
            ],
            [
                'group' => 'mail',
                'key' => 'mail.host',
                'value' => 'smtp.tino.vn',
                'type' => 'string',
                'label' => 'Máy chủ SMTP',
                'description' => 'Tên máy chủ SMTP dùng để gửi email.',
                'is_public' => false,
                'is_encrypted' => false,
                'autoload' => true,
                'sort_order' => 150,
            ],
            [
                'group' => 'mail',
                'key' => 'mail.encryption',
                'value' => 'tls',
                'type' => 'string',
                'label' => 'Mã hóa kết nối',
                'description' => 'Kiểu mã hóa kết nối tới máy chủ SMTP.',
                'is_public' => false,
                'is_encrypted' => false,
                'autoload' => true,
                'sort_order' => 160,
            ],
            [
                'group' => 'mail',
                'key' => 'mail.port',
                'value' => '587',
                'type' => 'integer',
                'label' => 'Cổng SMTP',
                'description' => 'Cổng kết nối tới máy chủ SMTP.',
                'is_public' => false,
                'is_encrypted' => false,
                'autoload' => true,
                'sort_order' => 170,
            ],
            [
                'group' => 'maintenance',
                'key' => 'maintenance.enabled',
                'value' => '0',
                'type' => 'boolean',
                'label' => 'Bật bảo trì',
                'description' => 'Trạng thái bật hoặc tắt chế độ bảo trì của hệ thống.',
                'is_public' => false,
                'is_encrypted' => false,
                'autoload' => true,
                'sort_order' => 180,
            ],
            [
                'group' => 'maintenance',
                'key' => 'maintenance.secret_key',
                'value' => '',
                'type' => 'string',
                'label' => 'Khóa bí mật bảo trì',
                'description' => 'Khóa bí mật dùng để truy cập hệ thống khi đang bảo trì.',
                'is_public' => false,
                'is_encrypted' => false,
                'autoload' => false,
                'sort_order' => 190,
            ],
            [
                'group' => 'maintenance',
                'key' => 'maintenance.message',
                'value' => '',
                'type' => 'string',
                'label' => 'Thông điệp bảo trì',
                'description' => 'Thông điệp hiển thị khi hệ thống đang ở chế độ bảo trì.',
                'is_public' => true,
                'is_encrypted' => false,
                'autoload' => true,
                'sort_order' => 200,
            ],
            [
                'group' => 'maintenance',
                'key' => 'maintenance.start_at',
                'value' => '',
                'type' => 'string',
                'label' => 'Thời gian bắt đầu bảo trì',
                'description' => 'Thời điểm bắt đầu áp dụng chế độ bảo trì.',
                'is_public' => false,
                'is_encrypted' => false,
                'autoload' => true,
                'sort_order' => 210,
            ],
            [
                'group' => 'maintenance',
                'key' => 'maintenance.end_at',
                'value' => '',
                'type' => 'string',
                'label' => 'Thời gian kết thúc bảo trì',
                'description' => 'Thời điểm kết thúc chế độ bảo trì.',
                'is_public' => false,
                'is_encrypted' => false,
                'autoload' => true,
                'sort_order' => 220,
            ],
        ];

        foreach ($settings as $setting) {
            Setting::query()->updateOrCreate(
                ['key' => $setting['key']],
                $setting,
            );
        }
    }
}
